name: CI

on:
  push:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Upload requirements.txt text File
      uses: actions/upload-artifact@v4
      with:
        name: requirements
        path: requirements.txt

    - name: Download requirment Text File
      uses: actions/download-artifact@v4
      with:
        name: requirements

    - name: Install dependencies
      run: |
        chmod +x requirements.txt
        pip install -r requirements.txt
        echo Hello GitHub Workflow
